//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LojaMateriaisParaConstrucao.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LMPCEntities1 : DbContext
    {
        public LMPCEntities1()
            : base("name=LMPCEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbFuncionario> tbFuncionarios { get; set; }
        public virtual DbSet<tbNivelAcesso> tbNivelAcessoes { get; set; }
        public virtual DbSet<tbUsuario> tbUsuarios { get; set; }
        public virtual DbSet<tbFornecedore> tbFornecedores { get; set; }
        public virtual DbSet<tbProduto> tbProdutoes { get; set; }
        public virtual DbSet<tbCliente> tbClientes { get; set; }
        public virtual DbSet<tbCargo> tbCargoes { get; set; }
        public virtual DbSet<tbCategoria> tbCategorias { get; set; }
        public virtual DbSet<tbDestinatario> tbDestinatarios { get; set; }
        public virtual DbSet<tbEstoque> tbEstoques { get; set; }
        public virtual DbSet<tbFormaPgto> tbFormaPgtoes { get; set; }
        public virtual DbSet<tbOrcamento> tbOrcamentoes { get; set; }
        public virtual DbSet<tbPedido> tbPedidoes { get; set; }
        public virtual DbSet<tbUnidadeVenda> tbUnidadeVendas { get; set; }
        public virtual DbSet<tbVenda> tbVendas { get; set; }
        public virtual DbSet<tbItem_Orcamento> tbItem_Orcamento { get; set; }
        public virtual DbSet<tbItem_Pedido> tbItem_Pedido { get; set; }
        public virtual DbSet<tbItem_Venda> tbItem_Venda { get; set; }
        public virtual DbSet<tbLancamento> tbLancamentoes { get; set; }
        public virtual DbSet<tbPeriodo> tbPeriodoes { get; set; }
        public virtual DbSet<tbPgto_Orcamento> tbPgto_Orcamento { get; set; }
        public virtual DbSet<tbPgto_Pedido> tbPgto_Pedido { get; set; }
        public virtual DbSet<tbPgto_Venda> tbPgto_Venda { get; set; }
        public virtual DbSet<tbTipoTitulo> tbTipoTituloes { get; set; }
        public virtual DbSet<tbContato> tbContatoes { get; set; }
        public virtual DbSet<tbCupom> tbCupoms { get; set; }
        public virtual DbSet<tbCupom_Cliente> tbCupom_Cliente { get; set; }
        public virtual DbSet<tbLog_Entrada_Produto> tbLog_Entrada_Produto { get; set; }
        public virtual DbSet<tbLog_Saida_Produto> tbLog_Saida_Produto { get; set; }
        public virtual DbSet<tbComentario> tbComentarios { get; set; }
    
        public virtual ObjectResult<pesq_cupom_Result> pesq_cupom(Nullable<int> codigoCliente)
        {
            var codigoClienteParameter = codigoCliente.HasValue ?
                new ObjectParameter("CodigoCliente", codigoCliente) :
                new ObjectParameter("CodigoCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pesq_cupom_Result>("pesq_cupom", codigoClienteParameter);
        }
    
        public virtual ObjectResult<produtosrecentes_Result> produtosrecentes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<produtosrecentes_Result>("produtosrecentes");
        }
    
        public virtual ObjectResult<sp_cupomadquirido_Result> sp_cupomadquirido()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_cupomadquirido_Result>("sp_cupomadquirido");
        }
    
        public virtual ObjectResult<sp_exibircomentarioproduto_Result> sp_exibircomentarioproduto(Nullable<int> codigoProduto)
        {
            var codigoProdutoParameter = codigoProduto.HasValue ?
                new ObjectParameter("CodigoProduto", codigoProduto) :
                new ObjectParameter("CodigoProduto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_exibircomentarioproduto_Result>("sp_exibircomentarioproduto", codigoProdutoParameter);
        }
    }
}
