//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LojaMateriaisParaConstrucao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbContato
    {
        public int CodigoContato { get; set; }
        public string NomeContato { get; set; }
        public string EmailContato { get; set; }
        public string AssuntoContato { get; set; }
        public string TelContato { get; set; }
        public Nullable<System.DateTime> DataContato { get; set; }
        public string Mensagem { get; set; }
        public Nullable<int> StatusContato { get; set; }
        public string Resposta { get; set; }
        public Nullable<int> CodigoUsuario { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
    }
}
