//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LojaMateriaisParaConstrucao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDestinatario
    {
        public int CodigoDestinatario { get; set; }
        public string NomeDestinatario { get; set; }
        public string EnderecoDestinatario { get; set; }
        public string BairroDestinatario { get; set; }
        public string CidadeDestinatario { get; set; }
        public string UFDestinatario { get; set; }
        public string CEPDestinatario { get; set; }
        public Nullable<int> NumeroDestinatario { get; set; }
        public string ComplementoDestinatario { get; set; }
        public string TelDestinatario { get; set; }
        public Nullable<bool> StatusDestinatario { get; set; }
    }
}
