//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LojaMateriaisParaConstrucao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLancamento
    {
        public int CodigoLancamento { get; set; }
        public int CodigoTitulo { get; set; }
        public System.DateTime DataVencimento { get; set; }
        public Nullable<decimal> ValorTitulo { get; set; }
        public Nullable<bool> StatusPagTitulo { get; set; }
        public Nullable<System.DateTime> DataPagamento { get; set; }
        public Nullable<decimal> ValorPagamento { get; set; }
        public Nullable<int> CodigoUsuario { get; set; }
    }
}
