//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LojaMateriaisParaConstrucao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbNivelAcesso
    {
        public int CodigoNivelAcesso { get; set; }
        public string NomeNivelAcesso { get; set; }
        public string Abreviacao { get; set; }
        public string Descricao { get; set; }
        public Nullable<bool> Permissao_Usuarios { get; set; }
        public Nullable<bool> Permissao_Clientes { get; set; }
        public Nullable<bool> Permissao_Funcionarios { get; set; }
        public Nullable<bool> Permissao_Fornecedores { get; set; }
        public Nullable<bool> Permissao_Produtos { get; set; }
        public Nullable<bool> Permissao_Contas { get; set; }
        public Nullable<bool> Permissao_Vender { get; set; }
        public Nullable<bool> Permissao_Orcamento { get; set; }
        public Nullable<bool> StatusNivel { get; set; }
    }
}
