//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LojaMateriaisParaConstrucao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbOrcamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbOrcamento()
        {
            this.tbItem_Orcamento = new HashSet<tbItem_Orcamento>();
        }
    
        public int CodigoOrcamento { get; set; }
        public Nullable<int> CodigoCliente { get; set; }
        public Nullable<int> CodigoFuncionario { get; set; }
        public Nullable<System.DateTime> DataOrcamento { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
    
        public virtual tbCliente tbCliente { get; set; }
        public virtual tbFuncionario tbFuncionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbItem_Orcamento> tbItem_Orcamento { get; set; }
    }
}
