//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LojaMateriaisParaConstrucao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPeriodo
    {
        public int CodigoPeriodo { get; set; }
        public string DescricaoPeriodo { get; set; }
        public Nullable<int> ValorPeriodo { get; set; }
        public string SinalPeriodo { get; set; }
        public Nullable<bool> StatusPeriodo { get; set; }
    }
}
