//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LojaMateriaisParaConstrucao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPgto_Orcamento
    {
        public int CodigoPgto_Orcamento { get; set; }
        public Nullable<int> CodigoFormaPgto { get; set; }
        public Nullable<int> CodigoOrcamento { get; set; }
        public Nullable<decimal> ValorForma { get; set; }
    
        public virtual tbFormaPgto tbFormaPgto { get; set; }
    }
}
