//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LojaMateriaisParaConstrucao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProduto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbProduto()
        {
            this.tbEstoques = new HashSet<tbEstoque>();
            this.tbItem_Orcamento = new HashSet<tbItem_Orcamento>();
            this.tbItem_Pedido = new HashSet<tbItem_Pedido>();
            this.tbItem_Venda = new HashSet<tbItem_Venda>();
            this.tbLog_Entrada_Produto = new HashSet<tbLog_Entrada_Produto>();
            this.tbLog_Saida_Produto = new HashSet<tbLog_Saida_Produto>();
            this.tbComentarios = new HashSet<tbComentario>();
        }
    
        public int CodigoProduto { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> CodigoUnidadeVenda { get; set; }
        public string CodigoBarra { get; set; }
        public Nullable<int> Quantidade { get; set; }
        public Nullable<int> EstoqueMinimo { get; set; }
        public Nullable<int> EstoqueMaximo { get; set; }
        public Nullable<int> CodigoFornecedor { get; set; }
        public Nullable<int> CodigoCategoria { get; set; }
        public Nullable<System.DateTime> DataEntrada { get; set; }
        public string Marca { get; set; }
        public string Imagem { get; set; }
        public Nullable<bool> StatusProduto { get; set; }
        public Nullable<decimal> ValorUnit { get; set; }
    
        public virtual tbFornecedore tbFornecedore { get; set; }
        public virtual tbCategoria tbCategoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEstoque> tbEstoques { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbItem_Orcamento> tbItem_Orcamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbItem_Pedido> tbItem_Pedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbItem_Venda> tbItem_Venda { get; set; }
        public virtual tbUnidadeVenda tbUnidadeVenda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLog_Entrada_Produto> tbLog_Entrada_Produto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLog_Saida_Produto> tbLog_Saida_Produto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbComentario> tbComentarios { get; set; }
    }
}
